### ISSUE TITLE
Error when running BlackboxGUI.py

### ISSUE THREAD

**Issue by chrisnick26** [yashraj9892/Automated-TV-show-Downloader#2]
I get this error when i try to run BlackboxGUI.py

python .\BlackboxGUI.py
Traceback (most recent call last):
  File ".\BlackboxGUI.py", line 2, in <module>
    import curses
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by yashraj9892** [comment]
Python for Windows doesn't come with curses. You need to visit http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses, download the version of curses that corresponds to your Windows and version of Python, and then pip install the whl file with the python you plan on using.

**Comment by yashraj9892** [comment]
please let me know if there is any other issue :)
